joycon_receiver:
  ros__parameters:
    forwardAxis: 1
    rotationAxis: 2
    forwardSpeedFactor: 80
    rotationSpeedFactor: 200
    forwardAxisInverted: true
    rotationAxisInverted: false
    standUpButton: 1
    layDownButton: 3
    printStatusButton: 2
    printLocationButton: 0
    period: 10 #in milliseconds
imu_reader:
  ros__parameters:
    gyroOffsetX: 3.734345 #in deg
    gyroOffsetY: -5.448233 #in deg
    gyroOffsetZ: -2.776097 #in deg
    angleCorrection: 0.089545 #in rad
    filterFactor: 0.05
    period: 10 #in milliseconds
tof_reader:
  ros__parameters:
      period: 100 #in milliseconds
motors_regulator:
  ros__parameters:
    microstep: 64
    maxSpeed: 400.0
    maxAcceleration: 15.0 #steps per period squared
    invertLeftMotor: true
    invertRightMotor: true
    enableSpeedPID: false
    pidSpeedKp: 0.0002
    pidSpeedInvTi: 0.0
    pidSpeedTd: 0.0
    pidAngleKp: 4000.0
    pidAngleInvTi: 5.0
    pidAngleTd: 0.01
    period: 10 # in milliseconds
odometry_calculator:
  ros__parameters:
    wheel_distance: 12.7 # cm
    wheel_radius: 5.5 # cm
    period: 10 # in milliseconds